/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:a3b8d0db-e385-41cf-82f9-b8bc2b50e8cf",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_w4XpC21W9",
    "aws_user_pools_web_client_id": "3ner0np611eis4bm0haluk0utp",
    "oauth": {
        "domain": "wobb4ae3e4d1-4ae3e4d1-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,wobb://",
        "redirectSignOut": "http://localhost:3000/,wobb://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ycc3vewhtjeglpvuhgnlzdvyrq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-vs5yvt73fbb4vfj45pq2kdhfv4",
    "aws_mobile_analytics_app_id": "1befe9030e224962b40d43905e1222ff",
    "aws_mobile_analytics_app_region": "ap-south-1",
    "aws_user_files_s3_bucket": "wobbs3bucket31436-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
